////
////  CreateProfile.swift
////  EarthquakeShakedown
////
////  Created by Kathryn Lee on 11/30/23.
////
//
//import SwiftUI
//
//struct CreateProfile: View {
//  var body: some View {
//    ZStack() {
//      Group {
//        Text("Create an Account")
//          .font(Font.custom("Raleway", size: 26).weight(.bold))
//          .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//          .offset(x: -43, y: -801)
//        Text("Build Your Profile")
//          .font(Font.custom("Raleway", size: 26).weight(.bold))
//          .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//          .offset(x: -51, y: -399)
//        Text("Name:")
//          .font(Font.custom("Lato", size: 20).weight(.light))
//          .foregroundColor(Color(red: 0.95, green: 0.86, blue: 0.75))
//          .offset(x: -113.50, y: -755.50)
//        Text("Birthdate:")
//          .font(Font.custom("Lato", size: 20).weight(.light))
//          .foregroundColor(Color(red: 0.95, green: 0.86, blue: 0.75))
//          .offset(x: -98, y: -591.50)
//        Text("Select Your Learning Goal")
//          .font(Font.custom("Lato", size: 20).weight(.light))
//          .foregroundColor(Color(red: 0.95, green: 0.86, blue: 0.75))
//          .offset(x: -0.50, y: -350.50)
//        Text("How would you describe your level of experience with earthquakes?")
//          .font(Font.custom("Lato", size: 20).weight(.light))
//          .foregroundColor(Color(red: 0.95, green: 0.86, blue: 0.75))
//          .offset(x: 1, y: 78.50)
//        Text("Email:")
//          .font(Font.custom("Lato", size: 20).weight(.light))
//          .foregroundColor(Color(red: 0.95, green: 0.86, blue: 0.75))
//          .offset(x: -113.50, y: -673.50)
//      }Group {
//        Text("mm/dd/yyyy")
//          .font(Font.custom("Lato", size: 20).weight(.light))
//          .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//          .offset(x: -64.50, y: -550.50)
//        Text("Current Location:")
//          .font(Font.custom("Lato", size: 20).weight(.light))
//          .foregroundColor(Color(red: 0.95, green: 0.86, blue: 0.75))
//          .offset(x: -64, y: -508.50)
//        Text("select one")
//          .font(Font.custom("Lato", size: 20).weight(.light))
//          .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//          .offset(x: -80.50, y: -467.50)
//        Rectangle()
//          .foregroundColor(.clear)
//          .frame(width: 315, height: 55)
//          .background(Color(red: 0.95, green: 0.86, blue: 0.75))
//          .cornerRadius(6)
//          .overlay(
//            RoundedRectangle(cornerRadius: 6)
//              .inset(by: 1)
//              .stroke(Color(red: 0.72, green: 0.60, blue: 0.42), lineWidth: 1)
//          )
//          .offset(x: -0.50, y: 155)
//      }Group {
//        Rectangle()
//          .foregroundColor(.clear)
//          .frame(width: 315, height: 55)
//          .background(Color(red: 0.95, green: 0.86, blue: 0.75))
//          .cornerRadius(6)
//          .overlay(
//            RoundedRectangle(cornerRadius: 6)
//              .inset(by: 1)
//              .stroke(Color(red: 0.72, green: 0.60, blue: 0.42), lineWidth: 1)
//          )
//          .offset(x: 0.50, y: 222)
//        Rectangle()
//          .foregroundColor(.clear)
//          .frame(width: 315, height: 55)
//          .background(Color(red: 0.95, green: 0.86, blue: 0.75))
//          .cornerRadius(6)
//          .overlay(
//            RoundedRectangle(cornerRadius: 6)
//              .inset(by: 1)
//              .stroke(Color(red: 0.72, green: 0.60, blue: 0.42), lineWidth: 1)
//          )
//          .offset(x: -0.50, y: 289)
//        Rectangle()
//          .foregroundColor(.clear)
//          .frame(width: 315, height: 55)
//          .background(Color(red: 0.95, green: 0.86, blue: 0.75))
//          .cornerRadius(6)
//          .overlay(
//            RoundedRectangle(cornerRadius: 6)
//              .inset(by: 1)
//              .stroke(Color(red: 0.72, green: 0.60, blue: 0.42), lineWidth: 1)
//          )
//          .offset(x: 0.50, y: 356)
//        Rectangle()
//          .foregroundColor(.clear)
//          .frame(width: 315, height: 55)
//          .background(Color(red: 0.95, green: 0.86, blue: 0.75))
//          .cornerRadius(6)
//          .overlay(
//            RoundedRectangle(cornerRadius: 6)
//              .inset(by: -1)
//              .stroke(Color(red: 0.72, green: 0.60, blue: 0.42), lineWidth: 1)
//          )
//          .offset(x: 0.50, y: 423)
//        Text("How would you describe your knowledge of earthquake preparedness?")
//          .font(Font.custom("Lato", size: 20).weight(.light))
//          .foregroundColor(Color(red: 0.95, green: 0.86, blue: 0.75))
//          .offset(x: 2, y: 510.50)
//        Rectangle()
//          .foregroundColor(.clear)
//          .frame(width: 315, height: 55)
//          .background(Color(red: 0.95, green: 0.86, blue: 0.75))
//          .cornerRadius(6)
//          .overlay(
//            RoundedRectangle(cornerRadius: 6)
//              .inset(by: 1)
//              .stroke(Color(red: 0.72, green: 0.60, blue: 0.42), lineWidth: 1)
//          )
//          .offset(x: 0.50, y: 587)
//        Rectangle()
//          .foregroundColor(.clear)
//          .frame(width: 315, height: 55)
//          .background(Color(red: 0.95, green: 0.86, blue: 0.75))
//          .cornerRadius(6)
//          .overlay(
//            RoundedRectangle(cornerRadius: 6)
//              .inset(by: 1)
//              .stroke(Color(red: 0.72, green: 0.60, blue: 0.42), lineWidth: 1)
//          )
//          .offset(x: 1.50, y: 654)
//        Rectangle()
//          .foregroundColor(.clear)
//          .frame(width: 315, height: 55)
//          .background(Color(red: 0.95, green: 0.86, blue: 0.75))
//          .cornerRadius(6)
//          .overlay(
//            RoundedRectangle(cornerRadius: 6)
//              .inset(by: 1)
//              .stroke(Color(red: 0.72, green: 0.60, blue: 0.42), lineWidth: 1)
//          )
//          .offset(x: 0.50, y: 721)
//        Rectangle()
//          .foregroundColor(.clear)
//          .frame(width: 315, height: 55)
//          .background(Color(red: 0.95, green: 0.86, blue: 0.75))
//          .cornerRadius(6)
//          .overlay(
//            RoundedRectangle(cornerRadius: 6)
//              .inset(by: 1)
//              .stroke(Color(red: 0.72, green: 0.60, blue: 0.42), lineWidth: 1)
//          )
//          .offset(x: 1.50, y: 788)
//        Rectangle()
//          .foregroundColor(.clear)
//          .frame(width: 315, height: 55)
//          .background(Color(red: 0.95, green: 0.86, blue: 0.75))
//          .cornerRadius(6)
//          .overlay(
//            RoundedRectangle(cornerRadius: 6)
//              .inset(by: -1)
//              .stroke(Color(red: 0.72, green: 0.60, blue: 0.42), lineWidth: 1)
//          )
//          .offset(x: 1.50, y: 855)
//      }Group {
//        ZStack() {
//          Rectangle()
//            .foregroundColor(.clear)
//            .frame(width: 150, height: 151)
//            .background(Color(red: 0.95, green: 0.86, blue: 0.75))
//            .cornerRadius(6)
//            .offset(x: 0, y: 0)
//          Text("Comprehensive\nEarthquake\nPreparedness")
//            .font(Font.custom("Lato", size: 18).weight(.bold))
//            .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//            .offset(x: -0.50, y: 0.50)
//        }
//        .frame(width: 150, height: 151)
//        .offset(x: -86, y: -64)
//        ZStack() {
//          Rectangle()
//            .foregroundColor(.clear)
//            .frame(width: 150, height: 151)
//            .background(Color(red: 0.95, green: 0.86, blue: 0.75))
//            .cornerRadius(6)
//            .offset(x: 0, y: 0)
//          Text("Be Prepared \nto Teach \nEarthquake 101 ")
//            .font(Font.custom("Lato", size: 18).weight(.bold))
//            .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//            .offset(x: -0.50, y: 0.50)
//        }
//        .frame(width: 150, height: 151)
//        .offset(x: 79, y: -64)
//        ZStack() {
//          Rectangle()
//            .foregroundColor(.clear)
//            .frame(width: 150, height: 151)
//            .background(Color(red: 0.95, green: 0.86, blue: 0.75))
//            .cornerRadius(6)
//            .offset(x: 0, y: 0)
//          Text("Review \nEarthquake\nProcedures")
//            .font(Font.custom("Lato", size: 18).weight(.bold))
//            .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//            .offset(x: -3, y: -0.50)
//        }
//        .frame(width: 150, height: 151)
//        .offset(x: 79, y: -234)
//        ZStack() {
//          Rectangle()
//            .foregroundColor(.clear)
//            .frame(width: 150, height: 151)
//            .background(Color(red: 0.95, green: 0.86, blue: 0.75))
//            .cornerRadius(6)
//            .offset(x: 0, y: 0)
//          Text("Gain Basic\nEarthquake \nKnowledge")
//            .font(Font.custom("Lato", size: 18).weight(.bold))
//            .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//            .offset(x: -0.50, y: 0.50)
//        }
//        .frame(width: 150, height: 151)
//        .offset(x: -86, y: -235)
//        ZStack() {
//          Rectangle()
//            .foregroundColor(.clear)
//            .frame(width: 142, height: 139)
//            .background(
//              AsyncImage(url: URL(string: "https://via.placeholder.com/142x139"))
//            )
//            .cornerRadius(101)
//            .offset(x: -61.11, y: 0)
//          Text("Earthquake \n")
//            .font(Font.custom("Raleway", size: 26))
//            .tracking(1.30)
//            .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//            .offset(x: -25.14, y: -14.08)
//          Text("Shakedown ")
//            .font(Font.custom("Raleway", size: 26))
//            .tracking(1.30)
//            .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//            .offset(x: 46.57, y: 28.04)
//        }
//        .frame(width: 264.21, height: 139)
//        .offset(x: -42.89, y: -925)
//        ZStack() {
//          Ellipse()
//            .foregroundColor(.clear)
//            .frame(width: 30, height: 30)
//            .background(Color(red: 0.95, green: 0.86, blue: 0.75))
//            .offset(x: 0, y: 0)
//          Text("?")
//            .font(Font.custom("Raleway", size: 22).weight(.bold))
//            .foregroundColor(Color(red: 0.72, green: 0.60, blue: 0.42))
//            .offset(x: 0, y: -3.13)
//        }
//        .frame(width: 30, height: 30)
//        .offset(x: 98, y: -800.50)
//        ZStack() {
//          Rectangle()
//            .foregroundColor(.clear)
//            .frame(width: 130, height: 40)
//            .background(Color(red: 0.95, green: 0.86, blue: 0.75))
//            .cornerRadius(6)
//            .overlay(
//              RoundedRectangle(cornerRadius: 6)
//                .inset(by: 0.50)
//                .stroke(Color(red: 0.41, green: 0.51, blue: 0.41), lineWidth: 0.50)
//            )
//            .offset(x: 0, y: 0)
//          Text("Submit")
//            .font(Font.custom("Raleway", size: 26).weight(.bold))
//            .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//            .offset(x: 0, y: -0.50)
//        }
//        .frame(width: 130, height: 40)
//        .offset(x: 0, y: 956.50)
//        Text("No earthquake experience")
//          .font(Font.custom("Lato", size: 18).weight(.light))
//          .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//          .offset(x: 1, y: 154.50)
//        Text("Very little exposure")
//          .font(Font.custom("Lato", size: 18).weight(.light))
//          .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//          .offset(x: 1.50, y: 221.50)
//        Text("Some experience")
//          .font(Font.custom("Lato", size: 18).weight(.light))
//          .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//          .offset(x: 0.50, y: 287.50)
//      }Group {
//        Text("Multiple experiences")
//          .font(Font.custom("Lato", size: 18).weight(.light))
//          .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//          .offset(x: 0.50, y: 355.50)
//        Text("Experienced many earthquakes")
//          .font(Font.custom("Lato", size: 18).weight(.light))
//          .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//          .offset(x: -0.50, y: 423.50)
//        Text("I know nothing about earthquakes")
//          .font(Font.custom("Lato", size: 18).weight(.light))
//          .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//          .offset(x: 3, y: 586.50)
//        Text("I know some general basics")
//          .font(Font.custom("Lato", size: 18).weight(.light))
//          .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//          .offset(x: 2.50, y: 653.50)
//        Text("I learned a little bit in school")
//          .font(Font.custom("Lato", size: 18).weight(.light))
//          .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//          .offset(x: -6, y: 720.50)
//        Text("I practiced in school but not recently")
//          .font(Font.custom("Lato", size: 18).weight(.light))
//          .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//          .offset(x: -2, y: 787.50)
//        Text("I take a refresher course every year")
//          .font(Font.custom("Lato", size: 18).weight(.light))
//          .foregroundColor(Color(red: 0.41, green: 0.51, blue: 0.41))
//          .offset(x: 0, y: 854.50)
//        ZStack() {
//          Rectangle()
//            .foregroundColor(.clear)
//            .frame(width: 25, height: 0)
//            .overlay(
//              Rectangle()
//                .stroke(Color(red: 0.95, green: 0.86, blue: 0.75), lineWidth: 0.50)
//            )
//            .offset(x: 0, y: -9)
//          Rectangle()
//            .foregroundColor(.clear)
//            .frame(width: 25, height: 0)
//            .overlay(
//              Rectangle()
//                .stroke(Color(red: 0.95, green: 0.86, blue: 0.75), lineWidth: 0.50)
//            )
//            .offset(x: 0, y: 0)
//          Rectangle()
//            .foregroundColor(.clear)
//            .frame(width: 25, height: 0)
//            .overlay(
//              Rectangle()
//                .stroke(Color(red: 0.95, green: 0.86, blue: 0.75), lineWidth: 0.50)
//            )
//            .offset(x: 0, y: 9)
//        }
//        .frame(width: 25, height: 18)
//        .offset(x: 157.50, y: -1003.50)
//        ZStack() {
//          Ellipse()
//            .foregroundColor(.clear)
//            .frame(width: 45, height: 45)
//            .background(Color(red: 0.67, green: 0.34, blue: 0.34))
//            .offset(x: 0, y: 0)
//          Text("?")
//            .font(Font.custom("Raleway", size: 30).weight(.bold))
//            .foregroundColor(Color(red: 0.95, green: 0.86, blue: 0.75))
//            .offset(x: 0, y: -3)
//        }
//        .frame(width: 45, height: 45)
//        .offset(x: 159.50, y: -245)
//      }
//    }
//    .frame(width: 390, height: 2075)
//    .background(Color(red: 0.95, green: 0.86, blue: 0.75));
//  }
//}
//
//struct CreateProfile_Previews: PreviewProvider {
//    static var previews: some View {
//        CreateProfile()
//    }
//}
